In [8]:
KNN Algorithm

[0 0 1 1]


In [9]:
X = [[0], [1], [2], [3]]
y = [0, 0, 1, 1]
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X,y)
print(neigh.predict([[0.9], [1.1], [2.1], [3.3]]))

[0 0 1 1]


In [7]:
Decision Tree Classifier

array([1])

In [10]:
from sklearn import tree
X = [[0,0],[1,1]]
Y = [0,1]
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X,Y)

clf.predict([[2,2]])

array([1])

In [ ]:
Support Vector Machines (SVM)

In [13]:
import numpy as np
X = np.array([[-1,-1], [-2,-1], [1,1], [2,1]])
y = np.array([1,1,2,2])
from sklearn.svm import SVC
clf = SVC()
clf.fit(X,y)
print(clf.predict([[-0.8,-1]]))

[1]
